### ISSUE TITLE
Suspicious single quote symbol in t/one/.envdesc

### ISSUE THREAD

**Issue by bessarabov** [mikkoi/env-assert#3]
Currently in the source code there is a file `t/one/.envdesc`

It looks like it is not used in tests, and there is one suspicious line in in:

`USER=^[[:word:]]{1,}$'`

I don't get it why there is a `'` in the end of that line. (Probably this is an error from copy-paste?)

**Comment by bessarabov** [comment]
And there is also single quote at the end of string in POD in script/envassert

```
FILENAME=^[[:word:]]{1,}$'
```

I'm not sure if it is right or not. I think that this is misspell, but I'm not 100% sure.

**Comment by mikkoi** [comment]
You are right. It is a typo left by me.
I have fixed them. Thank you.
And thanks for the two PRs. I have merged them and I just released a new version.

**Comment by bessarabov** [comment]
Ok. Now everything is clear. Thank you!
